[package]
name = "library"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10"
actix-codec = "0.3"
actix-web = "3"
actix-web-actors = "3"
actix-files = "0.3"
awc = "2"
env_logger = "0.8"
futures = "0.3.1"
bytes = "0.5.3"
rand = "0.7"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
embedded-hal = "0.2"
nb = "1"
linux-embedded-hal = "0.3"
embedded-ccs811 = "0.2.0"
diesel = { version = "^1.4.7", features = ["sqlite", "r2d2", "numeric"] }
diesel_migrations = "1.4.0"
libsqlite3-sys = { version = "0.17.3", features = ["bundled"] }
failure = "0.1.8"
r2d2 = "0.8"
askama = "0.9"
